.PHONY: clean All

All:
	@echo "----------Building project:[ textsearch - Debug ]----------"
	@cd "textsearch" && "$(MAKE)" -f  "textsearch.mk"
clean:
	@echo "----------Cleaning project:[ textsearch - Debug ]----------"
	@cd "textsearch" && "$(MAKE)" -f  "textsearch.mk" clean
