.PHONY: clean All

All:
	@echo "----------Building project:[ CreditCalculator - Debug ]----------"
	@cd "CreditCalculator" && "$(MAKE)" -f  "CreditCalculator.mk"
clean:
	@echo "----------Cleaning project:[ CreditCalculator - Debug ]----------"
	@cd "CreditCalculator" && "$(MAKE)" -f  "CreditCalculator.mk" clean
