.PHONY: clean All

All:
	@echo "----------Building project:[ carpetcleaningestimate - Debug ]----------"
	@cd "Project1" && "$(MAKE)" -f  "carpetcleaningestimate.mk"
clean:
	@echo "----------Cleaning project:[ carpetcleaningestimate - Debug ]----------"
	@cd "Project1" && "$(MAKE)" -f  "carpetcleaningestimate.mk" clean
